In [1]:
import torch

In [6]:
# Создаем случайный FloatTensor размера 3x4x5
random_tensor = torch.randn(3, 4, 5)
random_tensor

tensor([[[ 1.3169, -0.9521,  1.0111, -1.1806, -1.0761],
         [-0.9619,  0.9501, -1.4280, -1.0918,  0.0741],
         [ 0.7737,  0.8095,  0.1958, -0.1967, -0.0051],
         [ 0.0322,  0.2119,  0.7124,  0.2878,  0.0564]],

        [[ 0.0228, -0.4917,  0.3374, -0.7351, -1.3387],
         [ 0.6831, -0.2667, -0.5310, -0.5048,  0.5440],
         [ 2.0801, -1.9520, -1.4782, -0.7276,  0.6505],
         [-0.9723,  0.9760, -1.0350, -0.5428,  1.0033]],

        [[ 1.6036, -0.9024, -1.7728, -0.2298,  1.4493],
         [ 1.8306,  0.4665, -0.2318, -0.1313, -0.5439],
         [ 0.6826,  0.0250, -0.6283, -0.1593, -0.6836],
         [ 2.4823,  0.0436,  0.8385,  1.2380, -0.1272]]])

In [7]:
# Выводим его форму (shape)
print(random_tensor.shape)

torch.Size([3, 4, 5])


In [13]:
# Изменяем форму на 6x10
reshaped_tensor = random_tensor.reshape(6, 10)
reshaped_tensor

tensor([[ 1.3169, -0.9521,  1.0111, -1.1806, -1.0761, -0.9619,  0.9501, -1.4280,
         -1.0918,  0.0741],
        [ 0.7737,  0.8095,  0.1958, -0.1967, -0.0051,  0.0322,  0.2119,  0.7124,
          0.2878,  0.0564],
        [ 0.0228, -0.4917,  0.3374, -0.7351, -1.3387,  0.6831, -0.2667, -0.5310,
         -0.5048,  0.5440],
        [ 2.0801, -1.9520, -1.4782, -0.7276,  0.6505, -0.9723,  0.9760, -1.0350,
         -0.5428,  1.0033],
        [ 1.6036, -0.9024, -1.7728, -0.2298,  1.4493,  1.8306,  0.4665, -0.2318,
         -0.1313, -0.5439],
        [ 0.6826,  0.0250, -0.6283, -0.1593, -0.6836,  2.4823,  0.0436,  0.8385,
          1.2380, -0.1272]])

In [17]:
# Определяем вектор
vector = torch.tensor([1, 4, 2, 2, 1])

# Поскольку размерность вектора (5), его нужно расширить до формы (6, 10).
# Для этого мы повторим его и затем расширим.
# Вектор будет расширен по оси 1 (вторая ось).
# Мы создаем новый вектор размером (6, 10), повторяя вектор по оси 1 и затем по оси 0.
expanded_vector = vector.repeat(2)  # Повторим вектор до длины 10
expanded_vector = expanded_vector.reshape(1, 10).expand(6, 10)  # Расширим до формы (6, 10)

# Умножаем тензор поэлементно
result_tensor = reshaped_tensor * expanded_vector
result_tensor

tensor([[ 1.3169e+00, -3.8082e+00,  2.0222e+00, -2.3611e+00, -1.0761e+00,
         -9.6192e-01,  3.8004e+00, -2.8560e+00, -2.1836e+00,  7.4139e-02],
        [ 7.7368e-01,  3.2382e+00,  3.9161e-01, -3.9349e-01, -5.0613e-03,
          3.2188e-02,  8.4763e-01,  1.4248e+00,  5.7552e-01,  5.6402e-02],
        [ 2.2796e-02, -1.9668e+00,  6.7490e-01, -1.4703e+00, -1.3387e+00,
          6.8308e-01, -1.0667e+00, -1.0620e+00, -1.0097e+00,  5.4400e-01],
        [ 2.0801e+00, -7.8078e+00, -2.9565e+00, -1.4552e+00,  6.5050e-01,
         -9.7232e-01,  3.9041e+00, -2.0701e+00, -1.0856e+00,  1.0033e+00],
        [ 1.6036e+00, -3.6095e+00, -3.5457e+00, -4.5961e-01,  1.4493e+00,
          1.8306e+00,  1.8660e+00, -4.6367e-01, -2.6264e-01, -5.4393e-01],
        [ 6.8256e-01,  1.0015e-01, -1.2567e+00, -3.1851e-01, -6.8357e-01,
          2.4823e+00,  1.7439e-01,  1.6771e+00,  2.4760e+00, -1.2716e-01]])

In [18]:
# Усечем тензор до размерности (6, 6)
truncated_tensor = reshaped_tensor[:, :6]

# Матрично умножаем на его транспонированную версию
result_tensor = torch.matmul(truncated_tensor, truncated_tensor.T)

print(result_tensor)

tensor([[ 7.1402,  0.6529,  2.4908,  4.1973, -1.8708, -1.2244],
        [ 0.6529,  1.3321, -0.1409, -0.1517,  0.2598,  0.5400],
        [ 2.4908, -0.1409,  3.1554, -0.4918, -0.6388,  2.5190],
        [ 4.1973, -0.1517, -0.4918, 12.2201,  7.0477, -0.4427],
        [-1.8708,  0.2598, -0.6388,  7.0477, 12.0330,  5.7758],
        [-1.2244,  0.5400,  2.5190, -0.4427,  5.7758,  7.5157]])


In [19]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
# Определяем переменные с флагом requires_grad=True
x = torch.tensor(1.0, requires_grad=True)
z = torch.tensor(0.5, requires_grad=True)
t = torch.tensor(2.0, requires_grad=True)

# Определяем функцию y
y = x**3 + z - 75*t

# Выполняем обратное распространение
y.backward()

# Выводим значения градиентов
print(f"Частная производная по x: {x.grad.item()}")
print(f"Частная производная по z: {z.grad.item()}")
print(f"Частная производная по t: {t.grad.item()}")

Частная производная по x: 3.0
Частная производная по z: 1.0
Частная производная по t: -75.0


In [20]:
# Создаем единичный тензор размером 5x6
tensor_ones = torch.ones(5, 6)

print(tensor_ones)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [21]:
# Переводим тензор в формат NumPy
numpy_array = tensor_ones.numpy()

print(numpy_array)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [22]:
# Определяем переменные с флагом requires_grad=True
x = torch.tensor(1.0, requires_grad=False)  # Входное значение (фиксированное)
w1 = torch.tensor(1.0, requires_grad=True)  # Параметр для оптимизации

# Определяем функцию y
def func(x, w1):
    return x**w1 - 2 * x**2 + 5

# Определяем оптимизатор
optimizer = torch.optim.SGD([w1], lr=0.01)

# Оптимизация
num_iterations = 1000
for _ in range(num_iterations):
    # Вычисляем значение функции
    y = func(x, w1)
    # Вычисляем градиенты
    y.backward()
    # Выполняем шаг оптимизации
    optimizer.step()
    # Обнуляем градиенты
    optimizer.zero_grad()
# Выводим оптимальное значение w1
print(f"Оптимальное значение w1: {w1.item()}")

Оптимальное значение w1: 1.0
